name: Docker Multi Platform Builds

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        # we keep this just in case we need to change
        platform: ${{ github.event_name == 'pull_request' && fromJSON('["linux/amd64"]') || fromJSON('["linux/amd64"]') }}
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}
          #image: tonistiigi/binfmt:qemu-v8.0.4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_PUSH_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}
      - name: Set Docker metadata
        id: ocean_node_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            oceanprotocol/ocean-node
            ghcr.io/oceanprotocol/ocean-node
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=ref,event=pr
          # type=semver,pattern={{major}}.{{minor}}
          # type=semver,pattern={{major}}
          # type=sha
      - name: Build and push to Docker Hub
        id: build_dockerhub
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          # tags: ${{ steps.ocean_node_meta.outputs.tags }}
          labels: ${{ steps.ocean_node_meta.outputs.labels }}
          outputs: type=image,name=oceanprotocol/ocean-node,push-by-digest=true,name-canonical=true,push=true
      - name: Build and push to GHCR
        id: build_ghcr
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          labels: ${{ steps.ocean_node_meta.outputs.labels }}
          outputs: type=image,name=ghcr.io/oceanprotocol/ocean-node,push-by-digest=true,name-canonical=true,push=true
      - name: Export digests
        run: |
          mkdir -p /tmp/digests
          dockerhub_digest="${{ steps.build_dockerhub.outputs.digest }}"
          ghcr_digest="${{ steps.build_ghcr.outputs.digest }}"
          touch "/tmp/digests/dockerhub-${dockerhub_digest#sha256:}"
          touch "/tmp/digests/ghcr-${ghcr_digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  build-arm:
    runs-on: ubuntu-24.04-arm
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        # we keep this just in case we need to change
        platform: ${{ github.event_name == 'pull_request' && fromJSON('["linux/arm64"]') || fromJSON('["linux/arm64"]') }}
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}
          #image: tonistiigi/binfmt:qemu-v8.0.4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_PUSH_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}
      - name: Set Docker metadata
        id: ocean_node_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            oceanprotocol/ocean-node
            ghcr.io/oceanprotocol/ocean-node
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=ref,event=pr
          # type=semver,pattern={{major}}.{{minor}}
          # type=semver,pattern={{major}}
          # type=sha
      - name: Build and push to Docker Hub
        id: build_dockerhub
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          # tags: ${{ steps.ocean_node_meta.outputs.tags }}
          labels: ${{ steps.ocean_node_meta.outputs.labels }}
          outputs: type=image,name=oceanprotocol/ocean-node,push-by-digest=true,name-canonical=true,push=true
      - name: Build and push to GHCR
        id: build_ghcr
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          labels: ${{ steps.ocean_node_meta.outputs.labels }}
          outputs: type=image,name=ghcr.io/oceanprotocol/ocean-node,push-by-digest=true,name-canonical=true,push=true
      - name: Export digests
        run: |
          mkdir -p /tmp/digests
          dockerhub_digest="${{ steps.build_dockerhub.outputs.digest }}"
          ghcr_digest="${{ steps.build_ghcr.outputs.digest }}"
          touch "/tmp/digests/dockerhub-arm64-${dockerhub_digest#sha256:}"
          touch "/tmp/digests/ghcr-arm64-${ghcr_digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs:
      - build
      - build-arm
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set Docker metadata
        id: ocean_node_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            oceanprotocol/ocean-node
            ghcr.io/oceanprotocol/ocean-node
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=ref,event=pr
          # type=semver,pattern={{major}}.{{minor}}
          # type=semver,pattern={{major}}
          # type=sha
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_PUSH_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}
      - name: Create manifest list and push to Docker Hub
        working-directory: /tmp/digests
        run: |
          TAGS=$(echo "${{ steps.ocean_node_meta.outputs.tags }}" | grep -E '^oceanprotocol/ocean-node' | sed 's/^/-t /' | tr '\n' ' ')
          DIGESTS=$(ls dockerhub-* | sed 's/dockerhub-/oceanprotocol\/ocean-node@sha256:/' | tr '\n' ' ')
          docker buildx imagetools create $TAGS $DIGESTS
      - name: Create manifest list and push to GHCR
        working-directory: /tmp/digests
        run: |
          TAGS=$(echo "${{ steps.ocean_node_meta.outputs.tags }}" | grep -E '^ghcr.io/oceanprotocol/ocean-node' | sed 's/^/-t /' | tr '\n' ' ')
          DIGESTS=$(ls ghcr-* | sed 's/ghcr-/ghcr.io\/oceanprotocol\/ocean-node@sha256:/' | tr '\n' ' ')
          docker buildx imagetools create $TAGS $DIGESTS
      - name: Inspect Docker Hub image
        run: |
          docker buildx imagetools inspect oceanprotocol/ocean-node:${{ steps.ocean_node_meta.outputs.version }}
      - name: Inspect GHCR image
        run: |
          docker buildx imagetools inspect ghcr.io/oceanprotocol/ocean-node:${{ steps.ocean_node_meta.outputs.version }}
